### ISSUE TITLE
Made a new contribution to OMPL. How to make it visible to Moveit!?

### ISSUE THREAD

**Issue by bnovoselnik** [moveit/moveit_planners#10]
Hello,

This not so much an issue as a question, so I'm sorry if I'm asking this in a wrong place.

OK, so I've been playing around with OMPL and I've implemented a modification of RRT\* algorithm. Now I'm wondering is there a way to make this algorithm visible to Moveit! package. Just a week or two weeks ago I was able to do this. This is what I've done:
1. Built OMPL from source with my contribution (let's call it MyPlanner) which I've placed to 'ompl/src/ompl/contrib/MyPlanner/'.
2. Modified "planning_context_manager.cpp" in Moveit!: 

added this line:

registerPlannerAllocator("geometric::MyPlanner", boost::bind(&allocatePlannerog::MyPlanner, _1, _2, _3)); 

to the method "ompl_interface::PlanningContextManager::registerDefaultPlanners()"
1. Copied include files for my OMPL contribution to '/opt/ros/groovy/include'. Copied OMPL library files to 'opt/ros/groovy/lib'.
2. Rebuilt Moveit! and that's it. It worked like a charm. I was able to see my planner in rviz and I was able to plan with it.

Today I tried doing the exact same thing but it's not working anymore :( I'm guessing something changed in a past few weeks with Moveit! package.

Thank you for your help in advance :-)
Branimir

**Comment by isucan** [comment]
Hey,

Sorry to hear this. This should work pretty much the same way. Make sure you apply your changes on a clean checkout though. The library ompl_interface_ros and ompl_interface have merged. Also make sure you do not have any moveit debs installed (since you are working from source). 
You also need to add an entry for your planner in the ompl_planning.yaml file, to make things show un in rviz.
Hope this helps.

**Comment by bnovoselnik** [comment]
I managed to make it work. After installing ros-groovy-moveit-source-build-deps, I've manually removed ros-groovy-moveit-ompl package and replaced it with my version of OMPL lib. After rebuilding moveit package form a clean checkout everything seems to be OK.

Thanks again :-)

**Comment by isucan** [comment]
cool. closing then.
