### ISSUE TITLE
planning_scene::PlanningScene’ has no member named ‘getCurrentStateUpdated’

### ISSUE THREAD

**Issue by andfil** [moveit/moveit_planners#14]
I've just checked out moveit sources using http://moveit.ros.org/wiki/index.php/Groovy/Installation

Making them gives:
moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp:98:60: error: ‘const class planning_scene::PlanningScene’ has no member named ‘getCurrentStateUpdated’

This code comes from the latest commit, so I assume that the just mentioned latest commit relies on some code that's not committed yet.

A possible alternative  is that the build process doesn't respect a correct build order, and tries to link to the version of library that was installed through the binary install before (rather than trying to build the packages in the correct order and using the locally built version), but my knowledge of the build process and moveit stack is limited. All I can confidently tell is that I've followed the instructions and the build failed, so tips and corrections are appreciated. Is there a way to build moveit without removing the binary moveit?

**Comment by isucan** [comment]
The code is actually there. You probably also have the moveit_core deb package installed. Having both source and deb at the same time does not work well yet -- some headers from the deb are found before the ones from source.

https://github.com/ros-planning/moveit_core/blob/groovy-devel/planning_scene/include/moveit/planning_scene/planning_scene.h

Please let me know if this is indeed the case.

**Comment by andfil** [comment]
That's correct, I have the deb. Is there a way to enforce catkin/make to look in the proper place (local sources)?

**Comment by isucan** [comment]
For now the safest thing is to remove the debs. I think the issue can be fixed, but we need to make sure the include order is correct for all packages. Closing this for now. Let me know if this needs to be reopen.
