### ISSUE TITLE
OMPL - Control number of points to generate on the path

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_planners#2]
In order to create smooth paths for physical robot arm execution I need to raise the number of interpolated points generated by OMPL.

File: ompl/core/ompl_interface/src/model_based_planning_context.cpp
Line: 243 
Code: pg.interpolate((std::size_t)floor(0.5 + pg.length() / max_solution_segment_length_));

**Comment by aleeper** [comment]
+1
This is somewhat of interest for doing teleop stuff at high rate, by the way.

**Comment by davetcoleman** [comment]
Can we bump things on the issue tracker? I just had to reapply my temporary fix to this, but I think if I tried to patch this issue myself I would do it wrong to "ompl standards" :)
