### ISSUE TITLE
sbpl_interface depends on 'planning_models'

### ISSUE THREAD

**Issue by ghost** [moveit/moveit_planners#24]
'planning_models' is from the old arm-navigation stack and is mentioned as depreciated on the ros pages.

Supposedly the functionality has been ported to moveit but I cannot find the equivalent for the RobotState conversions?

I am migrating from groovy to hydro, and as our existing code uses sbpl I get this error when compiling moveit_planners;

```
[rospack] Error: package/stack 'sbpl_interface' depends on non-existent package 'planning_models' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
```

Am I missing something here? Should I just use the arm-navigation groovy branch?

**Comment by davetcoleman** [comment]
As far as I know, SBPL has not been migrated to catkin / hydro, as can be seen by the lack of package.xml in [sbpl_interface_ros](https://github.com/ros-planning/moveit_planners/tree/hydro-devel/sbpl/ros/sbpl_interface_ros). Any contributions to get this working again would be very appreciated!

**Comment by sssmanufacturing** [comment]
Ok. I have it mostly working now. Will test it then submit a pull request. Thanks

**Comment by mikeferguson** [comment]
Closing this, see #57
