### ISSUE TITLE
Planner plugins can't have their namespace "pushed down"

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_planners#3]
My use case is to have two different planning pipelines, say one for ompl and one for my stuff, called cat. The problem is that planner plugins assume the configuration parameters will be found in the home namespace, which doesn't allow for different configurations for different planner instances.

Some more detail: I load the plugin parameters in namespace ~/ompl and ~/cat. The planning pipelines take arguments for what the parameter names are, so you can prepend ompl/ and cat/ to the strings. However, the actual planner plugins assume they will find the planner configurations in the home namespace. There needs to be some way of telling the plugin that it has been pushed down into another namespace.

**Comment by isucan** [comment]
Fixed
https://github.com/ros-planning/moveit_planners/commit/bc88aebcad2d3e2d595e7e8cae3ffb3eaedf60c6
