### ISSUE TITLE
RRT* (RRTStar) segfault in MoveIt OMPL interface on allocation

### ISSUE THREAD

**Issue by arjungm** [moveit/moveit_planners#37]
I was trying to benchmark the RRT\* algorithm from MoveIt and I encountered a segfault when the planner is being setup by the context manager.
1. ompl::geometric::SimpleSetup calls allocatePlanner, [here](https://github.com/ompl/ompl/blob/master/src/ompl/geometric/src/SimpleSetup.cpp#L101-111) @ line 101, and then sets the ProblemDefinition @ line 109
2. allocatePlanner calls the planner setup(), [here](https://github.com/ros-planning/moveit_planners/blob/hydro-devel/ompl/ompl_interface/src/planning_context_manager.cpp#L126) @ line 126
3. setup tries to use ProblemDefinition before it is set, [here](https://github.com/ompl/ompl/blob/master/src/ompl/geometric/planners/rrt/src/RRTstar.cpp#L94-95) @ line 94

Maybe we should check if pdef_ exists in setup(), and if not, put setup_ back to false so that requires planner needs to be setup again. 

Maybe this should be in OMPL instead of MoveIt, actually... thoughts?

**Comment by mamoll** [comment]
The code in OMPL could be made more robust and we could check if pdef_ is non-NULL, but perhaps setup() shouldn't be called in allocatePlanner. @isucan might have some ideas why this is done this way in MoveIt! This isn't done in OMPL / OMPL.app, which is why haven't run into this before.

**Comment by davetcoleman** [comment]
Considering this doesn't occur with other planners, this problem is probably unique to RRT\* and the ordering in which it configures itself...

**Comment by arjungm** [comment]
Sorry I didn't follow up on this immediately. I don't think the [recent pull request Dave made](https://github.com/ompl/ompl/pull/22) fixes the issue because or the order of operations in allocatePlanner. 

I managed to work around this in OMPL, by checking if pdef_ is non-NULL, off of Mark's suggestion and made a [pull request here](https://github.com/ompl/ompl/pull/27).

**Comment by arjungm** [comment]
Got merged: https://github.com/ompl/ompl/pull/27

Closing this.
