### ISSUE TITLE
RRTconnect with 6DOF pose goal in 30s planning time returns failure after 2s

### ISSUE THREAD

**Issue by arjungm** [moveit/moveit_planners#44]
Parallel issue in OMPL
https://bitbucket.org/ompl/ompl/issue/92/rrtconnect-with-6dof-pose-goal-in-30s
### Problem

I'm running RRTconnect through MoveIt on the PR2 and I provided it with a 6DOF goal pose and a 30 second planning time.

However the planner returns, stating failure to sample any valid states from the goal tree after **2** seconds.

Shouldn't it keep trying to sample a goal state for 30 seconds?
### Details

The inheritance hierarchy in OMPL and MoveIt for this is as follows.

```
ompl_interface::ConstrainedGoalSampler
ompl::base::GoalLazySamples
ompl::base::GoalStates
ompl::base::GoalSampleableRegion
ompl::base::GoalRegion
ompl::base::Goal
```

GoalSampleableRegion has 3 virtual methods:
- **maxSampleCount**: number of times you can sample until you repeat
- **canSample** : returns true if maxSampleCount > 0
- **couldSample** : returns true if sampling_thread_ is running

For GoalStates:
- **maxSampleCount** returns the number of states in its member list.
- **canSample** not implemented
- **couldSample** not implemented

For GoalLazySamples:
- **maxSampleCount** not implemented
- **canSample** not implemented
- **couldSample** not implemented

For ConstrainedGoalSampler:
- **maxSampleCount** not implemented
- **canSample** not implemented
- **couldSample** not implemented

Here is the part where the planner essentially blocks until a goal sample is available:
[ob::PlannerInputStates::nextGoal(const PlannerTerminationCondition &ptc) line 268](https://bitbucket.org/ompl/ompl/src/bdf6bfd08a0b4cd3b72f621a12f9c8ae3d02ab32/src/ompl/base/src/Planner.cpp?at=default#cl-268)

Here `goal` is pointing to a `ConstrainedGoalSampler` instance.

You can see it makes a call to `GoalSampleableRegion::maxSampleCount()`, which calls `GoalStates::maxSampleCount()` which returns states_.size()
This is zero because no valid states have been sampled yet.

Additionally `GoalSampleableRegion::canSample()` resolves to `GoalSampleableRegion::canSample()`, which returns the result of maxSampleCount() > 0
Which also is false.

[GoalLazySamples.h](https://bitbucket.org/ompl/ompl/src/bdf6bfd08a0b4cd3b72f621a12f9c8ae3d02ab32/src/ompl/base/goals/GoalLazySamples.h?at=default)

[GoalStates.h](https://bitbucket.org/ompl/ompl/src/bdf6bfd08a0b4cd3b72f621a12f9c8ae3d02ab32/src/ompl/base/goals/GoalStates.h?at=default)

[GoalSampleableRegion.h](https://bitbucket.org/ompl/ompl/src/bdf6bfd08a0b4cd3b72f621a12f9c8ae3d02ab32/src/ompl/base/goals/GoalSampleableRegion.h?at=default)

As a result of this [Line 290 in Planner.cpp](https://bitbucket.org/ompl/ompl/src/bdf6bfd08a0b4cd3b72f621a12f9c8ae3d02ab32/src/ompl/base/src/Planner.cpp?at=default#cl-290) is never true.

I'm not sure if this is the reason why the planner exits early though...

Perhaps the fix here is to add the virtual methods to `ompl::base::GoalLazySamples` and implement them in `ompl_interface::ConstrainedGoalSampler` ?

**Comment by ryanluna** [comment]
The ConstrainedGoalSampler will only attempt to sample a finite number of states (default is 1000) before declaring failure.  This parameter is stored in the PlanningContext, a MoveIt concept, not an OMPL concept.  If every goal state is invalid, the goal sampler stops sampling and RRTConnect quits early because there is no root for the goal tree.

Since no valid goal states are sampled, I suspect a problem with how you construct your goal constraints.

**Comment by arjungm** [comment]
Thanks for your comment! That explains why it only tries 1000 calls to IK.

I thought my goal pose was incorrect at first, but I derived the 6DOF goal pose from a collision-free set of joint positions in the planning scene (just moving arms around with interactive markers).

It bears some investigation if there's a mismatch in the goal pose it is trying to solve an IK for in the Goal Sampling Thread, and the goal pose I grabbed from the scene. I will try this out, and report back!

**Comment by arjungm** [comment]
Alright so I managed to figure out why I wasn't able to find an IK for a pose that should most definitely have a solution.

In the goal sampling thread, an [outer loop](https://github.com/ros-planning/moveit_planners/blob/hydro-devel/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp#L81) iterates 1000 times (default) calling [`constraint_samplers::ConstrainedSampler::project`](https://github.com/ros-planning/moveit_planners/blob/hydro-devel/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp#L93).

The method resolves to [`constraint_samplers::IKConstraintSampler::project`](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L531).

This calls [`IKConstraintSampler::sampleHelper`](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L492) with the `project` argument as true.

Then in the method, it [loops](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L504) 4 times (default) and calls [`IKConstraintSampler::callIK`](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L525) each time. Note the last argument is (`project && a==0`). 

This means [`IKConstraintSampler::callIK`](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L544) is called with the `use_as_seed` argument as true the first inner iteration, and then false for the remaining attempts in loop in `IKConstraintSampler::sampleHelper`.

Inside `IKConstraintSampler::callIK`, it checks if there is a StateValidityCallback available. If so, it runs inverse kinematics with the callback. If not, it runs IK without checking for collisions, [Line 564](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L564).

Because `adapted_ik_validity_callback` is not available, then the search for IK is done and a solution is found (possibly in collision). Because `use_as_seed` is true, it uses the passed in state as a seed.

Then it saves the solution **back** into the state passed in as a seed. This state is a reference to `workstate` from before.

Then it always returns true back to [`IKConstraintSampler::sampleHelper`](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L525) which then exits out of the inner loop immediately and returns true back to the outer loop in [`ConstrainedGoalSampler::sampleUsingConstraintSampler`](https://github.com/ros-planning/moveit_planners/blob/hydro-devel/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp#L93).

From here it checks for collisions.

If the collision check fails, it loops for another attempt and passes the `workstate` that is initialized to the previous IK solution (which is in collision) to `IKConstrainstSampler::callIK` as the seed because `project && a==0` is true for the first inner attempt.

`callIK` returns the same solution as before, leading to a cycle that exhausts all 1000 attempts, and it never uses a randomized state because each `callIK` succeeded ( a solution was found ).

I attempted a fix for this issue and found that it let's RRTConnect succeed in planning to positions that are kind of cramped, where as before it would just declare failure to find an IK.

Pull requests incoming.

**Comment by arjungm** [comment]
Here's the pull requests that should fix it:

Adds a bool flag that forces random seed to ConstrainedSampler::project and its derived classes
https://github.com/ros-planning/moveit_core/pull/188

Makes use of above bool flag, after failing to sample a goal once
https://github.com/ros-planning/moveit_planners/pull/46

**Comment by davetcoleman** [comment]
Great write up! I'm trying to understand your issue, see comments in first PR.

**Comment by arjungm** [comment]
In this most recent pull request, you don't need to change the moveit_core classes for constraint samplers.

Instead, by setting the validity callback function means that randomization of the seed will be taken care of by IKConstraintSampler if it fails to find a valid IK.

[Line 525](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L525) the call to IK is made. `a==0` so the current state is used as a seed.
[Line 564](https://github.com/ros-planning/moveit_core/blob/hydro-devel/constraint_samplers/src/default_constraint_samplers.cpp#L564) the searchPositionIK uses the validity callback because it is set.

If the state it finds is invalid, it will correctly return false. Then it will loop again to Line 525 and now a!=0 so the use_as_seed flag is now false. This triggers a random seed for the remaining iterations.

**Comment by mikeferguson** [comment]
looks like this was fixed
