### ISSUE TITLE
OMPL's getDefaultPlanner changed location breaks moveit planners

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_planners#54]
This commit from the latest OMPL will potentially break MoveIt!
https://github.com/ompl/ompl/commit/78f5b686b2433069b32bb50e60985e7dad8cf9be#commitcomment-7855991

IMHO we should leave getDefaultPlanners in OMPL's SimpleSetup in the short run, marked as Deprecated, and have it call the new location one. Otherwise its going to be tricky with using the latest OMPL with MoveIt!. Proper tick-tocking would be nice.

@mamoll

**Comment by davetcoleman** [comment]
@mamoll said: Restored deprecated functions in https://github.com/ompl/ompl/commit/0ce70f9331dda65741c5598c2c22ae5eec907188

So this is the fix for MoveIt! so that the deprecated warning won't happen:
https://github.com/davetcoleman/moveit_planners/commit/57d68a7bac43de5d0dfeadd76c04b05e88946db9

I'm not sure where to merge it. Will the latest of OMPL be release for Indigo? Should I put it in a ROS-J branch? @isucan

**Comment by isucan** [comment]
I think we should update this for MoveIt indigo. We won't upgrade OMPL for hydro any more, but we might for indigo.

**Comment by davetcoleman** [comment]
+1 for updating Indigo - otherwise all of my research / dev this summer won't work for the next 4 years LTS

**Comment by davetcoleman** [comment]
This was fixed long ago
