### ISSUE TITLE
Revive SBPL interface

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_planners#57]
This ticket is simply to let folks know that I'm working on this (err, I have been working on this for far too long already.....) in conjunction with the guys at the SBPL lab. The updated interface should provide significant improvements to available motion primitives. I hope to have a PR ready shortly after the new year.

I've recently released SBPL into Indigo, and current work on the plugin is going on in my sandbox: https://github.com/mikeferguson/sandbox/tree/hydro-devel/sbpl_interface. The final code/API will depend on https://github.com/ros-planning/moveit_core/issues/215

**Comment by davetcoleman** [comment]
:gift: yay!

**Comment by isucan** [comment]
awesome! +10000

**Comment by mikeferguson** [comment]
Replaced by https://github.com/ros-planning/moveit/issues/101
