### ISSUE TITLE
OMPL plugins fail to load with current git version

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_planners#6]
Since https://github.com/ros-planning/moveit_planners/commit/6b6dca166d70440879f6d09c688681f15092e354 ,the ompl plugin fails to load for my robot setup generated with the setup assistant. Using the groovy-devel branch, some breakage is probably expected, but I figured filing a ticket can't hurt, in case issue was overlooked.

**Comment by isucan** [comment]
Hey, the plugin name changed. If you have your own generated config for the setup assistant, open ompl_planning_pipeline.launch and change the planner plugin name from ompl_interface_ros/OMPLPlanner to ompl_interface/OMPLPlanner. Let us know if this works? I will send out an e-mai if this fixes the issue.

**Comment by skohlbr** [comment]
Just wanted to change it, but my ompl_planning_pipeline.launch already has "ompl_interface/OMPLPlanner" in it (I regenerated config earlier today, before the breaking change). Using this launch file also works with https://github.com/ros-planning/moveit_planners/commit/71cdc9ae11418afc6d52a43e32f3e63733509105 .

The error I get with https://github.com/ros-planning/moveit_planners/commit/6b6dca166d70440879f6d09c688681f15092e354 is:

<pre>
[ERROR] [1365288343.036054637]: Exception while loading planner 'ompl_interface_ros/OMPLPlanner': According to the loaded plugin descriptions the class ompl_interface_ros/OMPLPlanner with base class type planning_interface::Planner does not exist. Declared types are  ompl_interface/OMPLPlanner
Available plugins: ompl_interface/OMPLPlanner 
</pre>

**Comment by isucan** [comment]
In the error msg it seems the namespace is incorrect.  I just updated the setup assistant to generate the correct plugin name.

**Comment by skohlbr** [comment]
Yes, works now, thanks for the quick fix! Also appears I misread the plugin name in my preceding reply (it indeed was "ompl_interface_ros/OMPLPlanner", not "ompl_interface/OMPLPlanner"). Sorry for any confusion resulting from that.

**Comment by haixuanwo** [comment]
hi，
I'm get the same problem "Exception while loading move_group capability 'move_group/MoveGroupCartesianPathService': Could not find library corresponding to plugin move_group/MoveGroupCartesianPathService. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
Available capabilities"

this is my config, "<arg name="planning_plugin" value="ompl_interface/OMPLPlanner" />"

 Do it seems the namespace is incorrect?
what should I do next?

**Comment by haixuanwo** [comment]
But , I can run rightly in using another urdf.
It is so strange.

**Comment by v4hn** [comment]
On Sat, Oct 08, 2016 at 06:16:54PM -0700, clark_linus wrote:

> But , I can run rightly in using another urdf.
> It is so strange.

This repository has been abandoned. Please use https://github.com/ros-planning/moveit .
Also, check http://moveit.ros.org/install/ and/or http://moveit.ros.org/install/source/
and verify your setup is up to date and consistent.

**Comment by haixuanwo** [comment]
thank v4hn for your response.
I find the reason about my quetion,it is that my computer doesn't have enough performance.
when I run in another better computer, It ok every time.
thanks gain.
