### ISSUE TITLE
MoveIt! package for schunk PG70 gripper

### ISSUE THREAD

**Issue by SaranKanag** [moveit/moveit_planners#71]
Hi, 

I am trying to control schunk PG70 gripper with MoveIt!. MoveIt! generally requires all dimensions to be in meters. I am currently using a package from [https://github.com/jlarraez/schunk_lwa4p] for PG70 integration. My PG70 is able to move only when i give a value in range 0.05 to 1.14 and it is an unknown unit. From spec, i could understand that PG70 can move from 0-68 mm(millimeters) so the value which it should move with respect to moveit is 0.00 to 0.068 meters. Now the package which i use is not moving the gripper at that required range instead it moves only for 0.05 to 1.14.

**Anyone please suggest me a way to move my gripper at its actual physical unit?  
Thanks in advance.**

**Comment by davetcoleman** [comment]
Sounds like you need to calibrate your gripper driver to accept meters as a unit, so that it can interface with MoveIt! properly. The simple ratio you explained would probably work. Seems out of scope of MoveIt! though, please re-open if I misunderstand.

**Comment by SaranKanag** [comment]
Thanks davetcoleman. 
I have resolved the issue by adding a joint named revolute joint for which the value i specified (0.05-1.14) can be given. Using this revolute joint we can map gripper's left finger and right finger values to lay within 0-68 mm.
