### ISSUE TITLE
Shortest path calculation in MoveIt

### ISSUE THREAD

**Issue by SaranKanag** [moveit/moveit_planners#72]
Hi,

When i am trying to execute a goal in MoveIt, i could see MoveIt resulting in longer trajectories most of the time. 

Without MoveIt in picture, I am able to execute shortest trajectory by giving only the shortest path computed (i.e. only goal joints positions) to actionClient "/arm/joint_trajectory_controller/follow_joint_trajectory" using actionlib.

I am trying to do the same using MoveIt. 
I also tried by giving the computed shortest path (goal joint position) using below code, but unexpectedly MoveIt again is planning a trajectory(set of points-path) for the same and it resulted in long trajectories again.

```
group_variable_values = group.get_current_joint_values()
group_variable_values[0] = -1.57
group_variable_values[1] = 1.0
group_variable_values[2] = 0.35
group_variable_values[3] = 0.567
group_variable_values[4] = 0.0
group_variable_values[5] = 2.2
group.set_joint_value_target(group_variable_values)
group.go(wait=True)
```

**So can any one help me in finding and providing shortest trajectory for goal execution using MoveIt.** 

Thanks in advance.

**Comment by davetcoleman** [comment]
this might belong as a question on the moveit-users email list...

either way, are you referring to straight line interpolation paths? i think we need more details on what you are trying to do.

**Comment by SaranKanag** [comment]
I have developed a pick and place application using a Schunk LWA4P arm. Object's co-ordinates will be given to robot using move group commander. So to reach that coordinates, I require MoveIt to plan a shorter trajectory?  

In MoveIt, we can plan and execute a goal using two different ways, one is by giving x,y,z values (geometric pose-stamp) and the other by giving joint values. When tried, i couldn't get shorter trajectories using both approaches.

**Comment by mikeferguson** [comment]
I concur this is probably a moveit-users email, closing as part of repo merging
